<?php

namespace KS\BlogBundle\Repository;

/**
 * GuestbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestbookRepository extends \Doctrine\ORM\EntityRepository
{

    public function orderGuestbookByDate() {

        $qb = $this->createQueryBuilder('g')
                ->orderBy('g.date', 'DESC')
                ->getQuery();

        return $qb->getResult();
    }
 


    /* La même requête en version SQL */ 
    
/*   
    public function orderGuestbookByDate() {

        $data = 'SELECT * FROM Guestbook  ORDER BY date ASC';

        $db = $this->getEntityManager()->getConnection()->prepare($data);
        $db->execute([]);

        return $db->fetchAll();
    } 
*/

}

