<?php

namespace KS\BlogBundle\Repository;

/**
 * InterviewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterviewsRepository extends \Doctrine\ORM\EntityRepository
{
}
