<?php

namespace KS\BlogBundle\Repository;

/**
 * NovelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NovelsRepository extends \Doctrine\ORM\EntityRepository
{
}
