<?php

namespace KS\BlogBundle\Repository;

/**
 * PartenariatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenariatsRepository extends \Doctrine\ORM\EntityRepository
{
}
