<?php

namespace KS\BlogBundle\Repository;

/**
 * SagasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SagasRepository extends \Doctrine\ORM\EntityRepository
{
}
